const ADD_BOARD = "ADD_BOARD"; //+
const UPDATE_BOARD = "UPDATE_BOARD"; //+
const REMOVE_BOARD = "REMOVE_BOARD"; //+

const ADD_LIST = "ADD_LIST"; //+
const REMOVE_LIST = "REMOVE_LIST"; //+
const MOVE_LIST = "MOVE_LIST"; //-
const UPDATE_LIST = "UPDATE_LIST"; //+

const ADD_TASK = "ADD_TASK"; //+
const REMOVE_TASK = "REMOVE_TASK"; //+
const MOVE_TASK = "MOVE_TASK"; //-
const UPDATE_TASK = "UPDATE_TASK"; //+

export default {ADD_BOARD, UPDATE_BOARD, REMOVE_BOARD, ADD_LIST, REMOVE_LIST, MOVE_LIST, UPDATE_LIST, ADD_TASK, REMOVE_TASK, MOVE_TASK, UPDATE_TASK}
